config/routes.rb
Rails.application.routes.draw do
 root 'users#index'
 
 resources :users
 resources :posts
 resources :comments
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments

	def full_name
		"#{self.first_name} #{self.last_name}"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :params_id, only: [:edit, :update, :show]

  def edit
  end

  def new
  	@comment = Comment.new
  end

  def update
  	@post = @comment.post
  	if @comment.update(comment_params)
  		redirect_to post_path(@post)
  	else
  		render :edit
  	end
  end

  def create
  	@comment = Comment.new(comment_params)
  	@post = Post.find(@comment.post_id)
  	if @comment.save
  		redirect_to post_path(@post)
  	else
  		render :new
  	end
	end

	def destroy
		comment = Comment.find(params[:id])
		post = Post.find(comment.post_id)
		if comments.destroy
			redirect_to post_path(post)
		else
			redirect_to comment_path(comment)
		end
	end

	def show
		@post = @comment.post
		@user = @comment.user
	end








  private

	  def params_id
	  	@comment = Comment.find(params[:id])
	  end

	  def comment_params
	  	params.require(:comment).permit(:opinion, :user_id, :post_id)
	  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all
    @users = User.all
  end

  def show
  	@post = Post.find(params[:id])
    @comments = @post.comments
    @user = User.find(@post.user_id)
  end

  def edit
  	@post = Post.find(params[:id])
  end

  def update
  	@post = Post.find(params[:id])
  	if @post.update(post_params)
  		redirect_to post_path(@post)
  	else
  		render :edit
    end
  end

  def new
    @user = User.find(params[:user_id])
    @post = Post.new
  end

  def create
  	@post = Post.new(post_params)
  	if @post.save
  		redirect_to posts_path
 	 	else
  		render :new
  	end
  end

  def destroy
  	@post = Post.find(params[:id])
  	if @post.destroy
  		redirect_to posts_path
  	else
  		redirect_to post_path(paths)
  	end
  end

  private

  def post_params
  	params.require(:post).permit(:content, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to users_path(@user)
  	else
  		render :edit
  	end
	end

	def destroy
		@user = User.find(params[:id])
		if @user.destroy
			redirect_to users_path
		else
			redirect_to user_path(@user)
		end
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to users_path
		else
			render :new
		end
	end



	private

	def user_params
		params.require(:user).permit(:first_name, :last_name, :age)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for @comment do |f| %>
	<%= f.label :opinion %>
	<%= f.text_area :opinion, placeholder: "Type your comment here ..." %>

	<%= f.hidden_field :post_id, value: params[:post_id] %>
	<%= f.hidden_field :user_id, value: params[:user_id] %>
	<br />
	<%= f.submit %>

<% end %>

app/views/comments/edit.html.erb
<h1> Edit your Comment </h1>

<%= render(partial: 'form') %>

app/views/comments/new.html.erb
<h1> New Comment </h1>

<%= render(partial: 'form') %>

app/views/layouts/_navbar.html.erb
<%= link_to 'User(s)', users_path %> | 
<%= link_to 'Post(s)', posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<%= f.label :content %>
<%= f.text_area :content, placeholder: "Type your new post here ..." %>
<%= f.hidden_field :user_id, value: params[:user_id] %>
<br />
<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Posts</h1>
<%= render(partial: 'form') %>

app/views/posts/index.html.erb
<h1>Post(s)</h1>
<% @posts.each do |post| %>
	<h4>This is a Post by: <%= post.user.full_name %></h4>
	
	<p><%= post.content %></p>
	<br />
	<%= link_to 'View Post', post_path(post) %> |
	<%= link_to 'Edit Post', edit_post_path(post, user_id: post.user_id) %>
	<br />
<% end %>
	<br />

<% @users.each do |user| %>
	<%= link_to "Create a New Post as #{user.first_name}", new_post_path(user_id: user.id) %>
	<br />
<% end %> 

	

app/views/posts/new.html.erb
<h1> New Posts  </h1>
<h2>As <%= @user.first_name %></h2>
<%= render(partial: 'form') %>

app/views/posts/show.html.erb
<h1> Posts </h1>
<p><%= @post.content %></p>
<br />
	<%= link_to 'Edit Post', edit_post_path(@post, user_id: @post.user_id) %> | 
	<%= link_to 'Delete Post', post_path(@post), method: :delete, data: { confirm: "Do you really want to delete this post?"} %> |
	<% @comments.each do |comment| %>
		<p><%= "{@user.first_name} #{}"
	<%= link_to 'Comment on Post', new_comment_path(post_id: @post.id, user_id: @user.id) %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<%= f.label :first_name %>
	<%= f.text_field :first_name %>
	<%= f.label :last_name %>
	<%= f.text_field :last_name %>
	<br />
	<%= f.label :age %>
	<%= f.select :age, (1..150) %>
	<br />
	<%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1> Edit a User </h1>
<hr />
<%= render(partial: 'form') %>

app/views/users/index.html.erb
<h1>User(s)</h1>
<% @users.each do |user| %>
	<h2><%= user.first_name %></h2>
	<h2><%= user.last_name %></h2>
	<h3><%= user.age %></h3>
	<%= link_to 'User Profile', user_path(user) %>
	<% end %>
	<h3><%= button_to 'New User', new_user_path, method: :get  %></h3>

app/views/users/new.html.erb
<h1> Create a New User </h1>
<hr />
<%= render(partial: 'form') %>

app/views/users/show.html.erb
<h1><%= @user.first_name %></h1>
<h1><%= @user.last_name %></h1>

<h3>Age: <%= @user.age %></h3>
<br />
<%= link_to 'Edit Profile', edit_user_path(@user) %>
<%= link_to 'Delete Profile', user_path(@user), method: :delete, data: { confirm: "Do you really want to delete this profile?"} %>